### ISSUE TITLE
Question about the "peft" and "requirements.txt"

### ISSUE THREAD

**Issue by TonAnh** [jyjohnchoi/SMoP#1]
Hi, I currently replicate your experiment but having some difficulties at the moment. 

1. In the train.py, you have this code. I wonder if this means I have to clone the HuggingFace PEFT library or if this is the folder "peft_models" in your code?

```
if "peft" not in os.getcwd():
    os.chdir("peft")
```
2. When running train.py, I got errors that modules such as "thop" or "tensorboardX" are missing. I have to install and rerun the code to check for each missing module, so I hope you can provide a requirements.txt for more convenience?

Thank you very much!

**Comment by jyjohnchoi** [comment]
Hello, thank you for showing interest in our work!
Below are responses regarding your difficulties:

1. It was to do with my root directory of the project (the name was 'peft'), and it has nothing to do with the HuggingFace PEFT library nor "peft_models" in our code. I will remove it in our updates, so you can just remove them and use it for now. Note that the code is structured to work without cloning the HuggingFace PEFT library.

2. Sorry for the inconvenience. I will add it when I update the codebase.

Please let me know if you have any further concerns!

**Comment by TonAnh** [comment]
Hi, thanks for your response. I currently have a new error, when I run the train.py, I get this 

> " File "/usr/local/lib/python3.8/dist-packages/datasets/table.py", line 64, in _memory_mapped_arrow_table_from_file
>     opened_stream = _memory_mapped_record_batch_reader_from_file(filename)
>   File "/usr/local/lib/python3.8/dist-packages/datasets/table.py", line 49, in _memory_mapped_record_batch_reader_from_file
>     memory_mapped_stream = pa.memory_map(filename)
>   File "pyarrow/io.pxi", line 898, in pyarrow.lib.memory_map
>   File "pyarrow/io.pxi", line 859, in pyarrow.lib.MemoryMappedFile._open
>   File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
>   File "pyarrow/error.pxi", line 113, in pyarrow.lib.check_status
> FileNotFoundError: [Errno 2] Failed to open local file '/my/user/.cache/huggingface/datasets/super_glue/boolq/1.0.3/bb9675f958ebfee0d5d6dc5476fafe38c79123727a7258d515c450873dbdbbed/super_glue-train.arrow'. Detail: [errno 2] No such file or directory"
> 

The error is traced back to the "superglue_loader.py" file. I changed the path like the code below, but I don't know what's causing the error because I thought it would read the train.pkl data. I hope to hear from you soon. Thank you very much.


```
def boolq(text_to_text):
    path = "/my/absolute/path/SMoP/data/superglue/boolq/"
    train = pickle.load(open(os.path.join(path, 'train.pkl'), 'rb'))
    val = pickle.load(open(os.path.join(path, 'validation.pkl'), 'rb'))

    if text_to_text:
        # https://huggingface.co/datasets/stjokerli/TextToText_boolq/viewer/stjokerli--TextToText_boolq/train
        text_format = f"boolq passage: **passage** question: **question**"
        labels = ("False", "True")
        train_list = [(text_format.replace("**passage**", d['passage']).replace("**question**", d['question']), labels[d['label']]) for d in train]
        val_list = [(text_format.replace("**passage**", d['passage']).replace("**question**", d['question']), labels[d['label']]) for d in val]
        num_labels = len(labels)
    else:
        train_list = [((d['question'], d['passage']), d['label']) for d in train]
        val_list = [((d['question'], d['passage']), d['label']) for d in val]
        num_labels = max(train['label']) + 1

    return train_list, val_list, num_labels
```

**Comment by jyjohnchoi** [comment]
First, please check whether you have properly downloaded and saved the dataset file in the .pkl format,
and if you have downloaded the dataset, try adding this code snippet at the top of your code:
```
if "your/absolute/path" not in os.getcwd():
    os.chdir("your/absolute/path")
```
If both of these solutions do not work, then the problem may lie in your Python settings regarding the path, so please consider checking it.
